spring:
  datasource:
    url: jdbc:mysql://120.25.145.41:3306/imusic
    username: root
    password: imusic-sql
    driver-class-name: com.mysql.jdbc.Driver
  resources:
      static-locations: classpath:static/,file:${spring.servlet.multipart.location}
  mvc:
      static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
  

server:
  port: 1234
